aids <- read.csv("http://www.stats.ox.ac.uk/~laws/SB1/data/aids.csv")
aids$qrt = as.factor(aids$qrt)
gm1 = glm(cases ~ date + qrt, data = aids, family = poisson)
gm2 = glm(cases ~ date + qrt, data = aids, family = poisson(link = sqrt))
anova(gm2, test="Chisq")
anova(gm2)
qqnorm(rstandard(gm2), pch=19, main="")
qqline(rstandard(gm2))
plot(predict(gm2,type="response"), rstandard(gm2))
pearson_stats = sum(residuals(gm2, type = "pearson")^2)
1-pchisq(pearson_stats,40)
plot(cooks.distance(gm2), pch = 19)
plot(aids$cases[aids$qrt == 1],pch=19, col="blue")
points(aids$cases[aids$qrt == 2],pch=19, col="red")
points(aids$cases[aids$qrt == 3],pch=19, col="green")
points(aids$cases[aids$qrt == 4],pch=19, col="yellow")